language: php
dist: trusty
php:
- '7.1'
before_install:
- openssl aes-256-cbc -K $encrypted_f7eb167194e1_key -iv $encrypted_f7eb167194e1_iv
  -in build/id_rsa.enc -out build/id_rsa -d
- chmod 0400 build/id_rsa
script:
- travis_retry composer install --no-interaction
- travis_retry composer update drutiny/website --no-interaction
- composer run-script build-api
deploy:
- provider: script
  script: "./build/publish-to-website.sh"
  skip_cleanup: true
  on:
    branch: master
    php: 7.1
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    secure: XHAEYTefk9HcpvTlKzo8p2JiEFFb1zmQKzuZGbWsatU0nEgvWQ91BeoMA3M7OIp8IYBKMvWDa0O94SJlU9mhRVDFdjWu1WvCNzHauwZA3J3K+MtHII9suCTfr/SsldhvqmIkXIL9QYqBTBNgZOZ7Ae539mjOZz+Ossmb2PbqeAqdhEMq/oMps0kptMEJKqYF+AoJEeflC+UMCr6GEhiibTI9eslpGbZY5atvQ02tWtZNZtPMl4aHVoCQ0vgAMXpSzLEKAwQfsAJUOqVfOSHqfDlULIQDlICNmruM3LQ6qFcCb3/GVi/N2+e8HKpBjTucOR5IsKLy1a8+jRzUMA7bgXGmEZPfD5X37GQEpZLOllbbhMbWRPo+jxdaHtUgBj6GI6ICgO3ftMFWJkH3SLJeqfQBxqinfLIZtNTyPcuIUMW2mOiXvxDtxJIuoPWPH3dbmxpo1LftYqjTJXdabeiYK3zaR2Lx6OfryLyhylfIjSobNAu7nbfwHeFPz7j+2FaUt+941wi2mzhdZS4GBIkMBDIo+G+DWq2GhMvsBOTEtFcatdht6PvbNYq/u/MfIqrAFBYnxCUZNO1PNJsG+1ipTtRiin+0H0UkJ7cxX/3IH4XDYYCeohlJ6BKLeyxQDdCTKWLBb1ccQhd4xtindCthwt9wQmFRPx2Fa2ZM7mzNL1M=
