# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-cli-jessie-browsers

    working_directory: /tmp/workspace

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install --no-interaction
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: composer update drutiny/website --no-interaction
      - run: composer run-script build-api
      - persist_to_workspace:
          root: .
          paths:
            - build
            - vendor/drutiny/website
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-cli-jessie-browsers
    working_directory: /tmp/workspace
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d4:ca:62:b4:37:97:bd:fd:2d:9d:d8:83:2d:e2:68:d8"
      - attach_workspace:
          at: /tmp/workspace
      - run: ssh-add -D
      - run: ssh-add ~/.ssh/id_rsa_d4ca62b43797bdfd2d9dd8832de268d8
      - deploy:
          command: ./build/publish-to-website.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
